In [17]:
# import pandas as pd
# from tkinter import Tk, filedialog
# from IPython.display import display

# root = Tk()
# root.withdraw()  # Hide the empty Tkinter window

# file_path = filedialog.askopenfilename(
#     title="Attach Bid List",
#     filetypes=[("Excel files", "*.xlsx")],
# )

# root.destroy()

# if file_path:
#     df = pd.read_excel(file_path)
#     display(df)
# else:
#     print("No file selected.")

In [ ]:
import pandas as pd
import io
import ipywidgets as widgets
from IPython.display import display, clear_output

# Create the upload button and space below it for messages
upload = widgets.FileUpload(accept='.xlsx', multiple=False)
output = widgets.Output()

# Function to display success when upload
def confirm_upload(change):
    with output:
        clear_output()
        if not upload.value:
            return

        # ipywidgets 8 uses a tuple; ipywidgets 7 uses a dictionary
        if isinstance(upload.value, dict):
            file_name = next(iter(upload.value))
        else:
            file_name = upload.value[0]['name']

        print(f"{file_name} attached.")

# Make upload button see the function
upload.observe(confirm_upload, names='value')

# Display button and space below 
display(upload, output)

FileUpload(value=(), accept='.xlsx', description='Upload')

Output()

In [3]:
# Extracts data from widget and make it a df
if upload.value:
    content = upload.value[0]['content']
    file_name = upload.value[0]['name']
    df = pd.read_excel(io.BytesIO(content))
    display(df)
else:
    print("No file attached yet.")



print(f"{file_name} Analysis")

prod_group = pd.DataFrame(df["Product Group"].unique())

display(prod_group)

,Bid(s),Product Group,Material,Batch,Gauge,Width,Weight lbs,PIW,Translated Grade,Comment,...,Foreign Mat. Index,Defect code text 2,Defect code text 3,Defect code text 4,Unrestricted,Weight Kg,Th,Width Of Pieces,Length Of Pieces,Density
0,NaN,AL,AL-SEC,4404062540,0.023,44.895,22421,499.409734,CS Type B,NaN,...,T,1602 Missing Identity,9962 SPM CROP,NaN,10170,10170,0.593,1140.33,1960,0.0077
1,NaN,AL,AL-SEC,5302055850,0.024,48.109,16931,351.929992,CS Type B,NaN,...,P,303 Weight Under,NaN,NaN,7680,7680,0.613,1221.98,1343,0.0076
2,NaN,AL,AL-SEC,5302062370,0.024,48.113,44621,927.420863,CS Type B,NaN,...,T,808 Dents,NaN,NaN,20240,20240,0.613,1222.07,3539,0.0076
3,NaN,AL,AL-SEC,4404062550,0.029,48.269,21869,453.065114,DDS,NaN,...,4,1108 Furnace Pressure,NaN,NaN,9920,9920,0.730,1226.03,1444,0.0077
4,NaN,AL,AL-SEC,4404062480,0.029,51.791,22751,439.284818,CS Type B,NaN,...,L,NaN,NaN,NaN,10320,10320,0.726,1315.48,1406,0.0077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,NaN,HRP,HRP-SEC,2104830960,0.247,60.589,45481,750.647807,Structural Steel 36 Type 2,NaN,...,P,822 Pits,1917 Scale Pitting,822 Pits,20630,20630,6.272,1538.95,273,0.0078
848,NaN,HRP,HRP-SEC,2504389320,0.379,60.630,45388,748.606301,HSLA 80,NaN,...,T,509 Telescope ID,828 Scratch,NaN,20588,20588,9.627,1540.00,180,0.0077
849,NaN,HRP,HRP-SEC,2504277160,0.496,60.600,58929,972.425743,Structural Steel 36 Type 2,NaN,...,3,9936 Remarks,302 Weight Over,9933 Planning,26730,26730,12.598,1539.24,178,0.0077
850,NaN,HRP,HRP-SEC,2504404760,0.621,60.630,45633,752.647204,HSLA 50,NaN,...,G,1804 Lamination,NaN,NaN,20699,20699,15.773,1540.00,110,0.0077
851,NaN,HRP,HRP-SEC,2504373510,0.631,60.330,46074,763.699652,HSLA 50,NaN,...,P,509 Telescope ID,1802 Gouge,303 Weight Under,20899,20899,16.027,1532.38,109,0.0078

8-24-2026 SP Inv.xlsx Analysis

      0
0    AL
1    CR
2  CRFH
3    GA
4    GI
5    HR
6   HRP